name: Auto Download TikTok Video

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Jalan setiap jam

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cek file video_url.txt
        run: |
          ls -lah
          if [ -f "video_url.txt" ]; then
            cat video_url.txt
          else
            echo "File video_url.txt tidak ditemukan!" && exit 1
          fi

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y yt-dlp

      - name: Download TikTok Video
        run: |
          VIDEO_URL=$(cat video_url.txt)
          yt-dlp -o "tiktok_video.mp4" "$VIDEO_URL"

      - name: Commit dan push perubahan
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update downloaded TikTok video" --allow-empty || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
          
