import requests
from bs4 import BeautifulSoup
import os

def download_facebook_video(url, output_path):
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        video_tag = soup.find('meta', {'property': 'og:video'})
        
        if video_tag:
            video_url = video_tag['content']
            video_response = requests.get(video_url)

            with open(output_path, 'wb') as file:
                file.write(video_response.content)
            print(f"Video downloaded successfully to {output_path}")
        else:
            print("Video URL not found on the provided Facebook page.")
    else:
        print(f"Failed to retrieve the page. Status code: {response.status_code}")

def download_videos_from_file(file_path, output_dir):
    with open(file_path, 'r') as file:
        urls = file.readlines()
    
    for i, url in enumerate(urls):
        url = url.strip()
        if url:
            output_file_path = os.path.join(output_dir, f"video_{i+1}.mp4")
            download_facebook_video(url, output_file_path)

# Contoh penggunaan
facebook_urls_file = 'facebook_urls.txt'
output_directory = '.'  # Menyimpan video di direktori utama repository
download_videos_from_file(facebook_urls_file, output_directory)
