name: Download TikTok Video

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'TikTok Video URL'
        required: true
        default: 'https://vm.tiktok.com/ZSMggXVNH/'

jobs:
  download_and_commit_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq

    - name: Get actual TikTok Video URL
      run: |
        # Menggunakan curl untuk mengarah ke URL video TikTok sebenarnya
        response=$(curl -sL "${{ github.event.inputs.url }}")
        video_url=$(echo "$response" | grep -oP 'video_url":"\K(.*?)(?=")')
        echo "Video URL is: $video_url"
        echo "::set-output name=video_url::$video_url"

    - name: Download TikTok Video
      run: |
        curl -L ${{ steps.Get_actual_TikTok_Video_URL.outputs.video_url }} -o video.mp4

    - name: Commit and Push Video to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add video.mp4
        git commit -m "Add TikTok video"
        git push
