name: Auto Download TikTok Video

on:
  push:  # Otomatis berjalan setiap ada perubahan di repo
  workflow_dispatch:  # Bisa dijalankan manual juga

permissions:
  contents: write  # Memberikan izin menulis ke repo

jobs:
  download_and_commit_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq

    - name: Resolve TikTok Video URL
      run: |
        echo "Resolving TikTok URL..."
        resolved_url=$(curl -Ls -o /dev/null -w %{url_effective} "https://vm.tiktok.com/ZSMggXVNH/")
        echo "Resolved URL: $resolved_url"
        if [[ -z "$resolved_url" ]]; then
          echo "Error: Failed to resolve TikTok URL."
          exit 1
        fi
        echo "VIDEO_URL=$resolved_url" >> $GITHUB_ENV

    - name: Download TikTok Video
      run: |
        echo "Downloading video from $VIDEO_URL..."
        curl -L "$VIDEO_URL" -o video.mp4
        if [ ! -s "video.mp4" ]; then
          echo "Error: Video download failed."
          exit 1
        fi

    - name: Commit and Push Video
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add video.mp4
        git commit -m "Auto-download TikTok video"
        git push || echo "No changes to commit"
