name: Auto Download TikTok Video

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Jalankan setiap 6 jam (opsional)
  workflow_dispatch: # Bisa dijalankan manual dari GitHub Actions

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yt-dlp
        run: |
          sudo apt update
          sudo apt install -y yt-dlp ffmpeg

      - name: Download TikTok Video
        run: |
          VIDEO_URL="https://vm.tiktok.com/ZSMggXVNH/"
          echo "Mengunduh video dari: $VIDEO_URL"
          yt-dlp -o "tiktok_video.mp4" "$VIDEO_URL"

      - name: Cek file hasil download
        run: |
          ls -lah
          file tiktok_video.mp4 || echo "Video tidak ditemukan!"

      - name: Commit dan push perubahan
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f tiktok_video.mp4
          git commit -m "Update downloaded TikTok video" || echo "Tidak ada perubahan untuk di-commit"
          git push origin main || echo "Gagal push, mungkin tidak ada perubahan"
