name: Auto Download TikTok Video

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download_and_commit_video:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl jq ffmpeg  # Tambahkan ffmpeg

    - name: Resolve TikTok Video URL
      run: |
        echo "Resolving TikTok URL..."
        resolved_url=$(curl -Ls -o /dev/null -w %{url_effective} "https://vm.tiktok.com/ZSMggXVNH/")
        echo "Resolved URL: $resolved_url"
        if [[ -z "$resolved_url" ]]; then
          echo "Error: Failed to resolve TikTok URL."
          exit 1
        fi
        echo "VIDEO_URL=$resolved_url" >> $GITHUB_ENV

    - name: Download TikTok Video (M3U8 Handling)
      run: |
        echo "Fetching direct video link..."
        video_direct_url=$(curl -s "$VIDEO_URL" | grep -oP 'playAddr":"\K(.*?)(?=")' | sed 's/\\u002F/\//g' | sed 's/\\u0026/&/g')
        echo "Direct video URL: $video_direct_url"
        
        if [[ -z "$video_direct_url" ]]; then
          echo "Error: Failed to extract direct video URL."
          exit 1
        fi

        echo "Downloading video..."
        ffmpeg -i "$video_direct_url" -c copy video.mp4
        
        if [ ! -s "video.mp4" ]; then
          echo "Error: Video download failed."
          exit 1
        fi

    - name: Commit and Push Video
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add video.mp4
        git commit -m "Auto-download TikTok video"
        git push || echo "No changes to commit"
        
